//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisSpec) DeepCopyInto(out *AnalysisSpec) {
	*out = *in
	out.Interval = in.Interval
	out.MaxStepDuration = in.MaxStepDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisSpec.
func (in *AnalysisSpec) DeepCopy() *AnalysisSpec {
	if in == nil {
		return nil
	}
	out := new(AnalysisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisState) DeepCopyInto(out *AnalysisState) {
	*out = *in
	out.Errors = in.Errors
	out.Latency = in.Latency
	if in.CheckpointStartedAt != nil {
		in, out := &in.CheckpointStartedAt, &out.CheckpointStartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastCounters != nil {
		in, out := &in.LastCounters, &out.LastCounters
		*out = new(CounterSnapshot)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisState.
func (in *AnalysisState) DeepCopy() *AnalysisState {
	if in == nil {
		return nil
	}
	out := new(AnalysisState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryRollout) DeepCopyInto(out *CanaryRollout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryRollout.
func (in *CanaryRollout) DeepCopy() *CanaryRollout {
	if in == nil {
		return nil
	}
	out := new(CanaryRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanaryRollout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryRolloutList) DeepCopyInto(out *CanaryRolloutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CanaryRollout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryRolloutList.
func (in *CanaryRolloutList) DeepCopy() *CanaryRolloutList {
	if in == nil {
		return nil
	}
	out := new(CanaryRolloutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanaryRolloutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryRolloutSpec) DeepCopyInto(out *CanaryRolloutSpec) {
	*out = *in
	out.SuccessCriteria = in.SuccessCriteria
	if in.StepPercentages != nil {
		in, out := &in.StepPercentages, &out.StepPercentages
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.Analysis != nil {
		in, out := &in.Analysis, &out.Analysis
		*out = new(AnalysisSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryRolloutSpec.
func (in *CanaryRolloutSpec) DeepCopy() *CanaryRolloutSpec {
	if in == nil {
		return nil
	}
	out := new(CanaryRolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryRolloutStatus) DeepCopyInto(out *CanaryRolloutStatus) {
	*out = *in
	if in.TargetReplicas != nil {
		in, out := &in.TargetReplicas, &out.TargetReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Analysis != nil {
		in, out := &in.Analysis, &out.Analysis
		*out = new(AnalysisState)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryRolloutStatus.
func (in *CanaryRolloutStatus) DeepCopy() *CanaryRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(CanaryRolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CounterSnapshot) DeepCopyInto(out *CounterSnapshot) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CounterSnapshot.
func (in *CounterSnapshot) DeepCopy() *CounterSnapshot {
	if in == nil {
		return nil
	}
	out := new(CounterSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriterionState) DeepCopyInto(out *CriterionState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriterionState.
func (in *CriterionState) DeepCopy() *CriterionState {
	if in == nil {
		return nil
	}
	out := new(CriterionState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuccessCriteria) DeepCopyInto(out *SuccessCriteria) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuccessCriteria.
func (in *SuccessCriteria) DeepCopy() *SuccessCriteria {
	if in == nil {
		return nil
	}
	out := new(SuccessCriteria)
	in.DeepCopyInto(out)
	return out
}
